Repository wazo-platform/wazo-call-logd, pull requests merged in 2020-11, with the labels that each got.

#75 queue: follow timezone to extract work hours/days
  integration_tests/suite/test_db_queue_stat.py
  wazo_call_logd/database/queries/queue_stat.py
  wazo_call_logd/plugins/support_center/api.yml
Labels: mergeit

#77 WAZO-2062: stat listing should show queues without data
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_db_queue_stat.py
  integration_tests/suite/test_queue_stats.py
  wazo_call_logd/database/queries/queue_stat.py
  wazo_call_logd/plugins/support_center/schema.py
  wazo_call_logd/plugins/support_center/service.py
Labels: mergeit

#78 stat: add a notice about stats generation
  wazo_call_logd/plugins/support_center/api.yml
Labels: mergeit

#76 Wazo 2045 agent stats by day
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_agent_stats.py
  integration_tests/suite/test_db_agent_stat.py
  integration_tests/suite/test_db_queue_stat.py
  wazo_call_logd/database/queries/__init__.py
  wazo_call_logd/database/queries/agent_stat.py
  wazo_call_logd/database/queries/queue_stat.py
  wazo_call_logd/plugins/support_center/api.yml
  wazo_call_logd/plugins/support_center/exceptions.py
  wazo_call_logd/plugins/support_center/plugin.py
  wazo_call_logd/plugins/support_center/resource.py
  wazo_call_logd/plugins/support_center/schema.py
  wazo_call_logd/plugins/support_center/service.py
Labels: mergeit

#80 Stat test homogenization
  integration_tests/suite/test_queue_stats.py
Labels: auto-merge

#81 bus: use correct policy for publishing
  wazo_call_logd/bus_publisher.py
Labels: auto-merge, mergeit

#82 Pull request for WAZO-2021-refactor-dao-injection
  tox.ini
  wazo_call_logd/controller.py
  wazo_call_logd/plugins/cdr/plugin.py
  wazo_call_logd/plugins/support_center/plugin.py
Labels: mergeit

#83 Pull request for WAZO-2101-add-deleted-col-to-stat-tables
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_db_queue_stat.py
  wazo_call_logd/database/queries/queue_stat.py
Labels: mergeit

#84 WAZO-2071: use geographical timezones
  CHANGELOG.md
  debian/control
  integration_tests/suite/test_db_agent_stat.py
  integration_tests/suite/test_db_queue_stat.py
  integration_tests/suite/test_queue_stats.py
  integration_tests/test-requirements-for-tox.txt
  requirements.txt
  wazo_call_logd/database/queries/agent_stat.py
  wazo_call_logd/database/queries/queue_stat.py
  wazo_call_logd/plugins/support_center/api.yml
  wazo_call_logd/plugins/support_center/schema.py
  wazo_call_logd/plugins/support_center/service.py
  wazo_call_logd/plugins/support_center/tests/test_service.py
Labels: mergeit

#85 Fix over 24 hours
  integration_tests/suite/test_agent_stats.py
  wazo_call_logd/database/queries/agent_stat.py
Labels: mergeit
