Repository wazo-platform/wazo-call-logd, pull requests merged in 2021-03, with the labels that each got.

#106 Pull request for fix-db-schema-difference
  integration_tests/suite/test_call_logd_migrate_db.py
  wazo_call_logd/database/alembic/versions/19f58ac91ae1_add_call_log_tables.py
  wazo_call_logd/main_migrate_db.py
  zuul.yaml
Labels: auto-merge

#104 WAZO-2273: delete multiple recordings
  CHANGELOG.md
  integration_tests/suite/test_cdr_recording.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/exceptions.py
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/plugin.py
  wazo_call_logd/plugins/cdr/schemas.py
Labels: mergeit

#109 Pull request for WAZO-2148-duplicate-call-participants
  README.md
  integration_tests/suite/test_call_log_generation.py
  integration_tests/suite/test_call_logs_cli.py
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_db_call_log.py
  integration_tests/suite/test_db_cel.py
  integration_tests/test-requirements-for-tox.txt
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/controller.py
  wazo_call_logd/generator.py
  wazo_call_logd/main_sweep.py
  wazo_call_logd/participant.py
  wazo_call_logd/plugins/support_center/tests/test_services.py
  wazo_call_logd/raw_call_log.py
  wazo_call_logd/tests/test_cel_interpretor.py
  wazo_call_logd/tests/test_generator.py
  wazo_call_logd/tests/test_participant.py
Labels: mergeit

#108 WAZO-2291: add recorded calls filter
  CHANGELOG.md
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_db_call_log.py
  wazo_call_logd/database/queries/call_log.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/schemas.py
Labels: mergeit

#110 freeze sqlalchemy version for tests
  integration_tests/test-requirements-for-tox.txt
Labels: auto-merge, mergeit
