Repository wazo-platform/wazo-call-logd, pull requests merged in 2021-02, with the labels that each got.

#93 Pull request for WAZO-2201-recording-metadata
  CHANGELOG.md
  README.md
  contribs/docker/Dockerfile-db
  debian/control
  debian/wazo-call-logd.config
  debian/wazo-call-logd.postinst
  debian/wazo-call-logd.templates
  etc/wazo-call-logd/config.yml
  integration_tests/Makefile
  integration_tests/assets/docker-compose.base.override.yml
  integration_tests/assets/docker-compose.database.override.yml
  integration_tests/assets/docker-compose.documentation.override.yml
  integration_tests/assets/docker-compose.no_rabbitmq.override.yml
  integration_tests/assets/docker-compose.yml
  integration_tests/assets/etc/wazo-call-logd/conf.d/50-default.yml
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_call_log_generation.py
  integration_tests/suite/test_call_logs_cli.py
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_db.py
  integration_tests/suite/test_db_recording.py
  integration_tests/suite/test_recording_generation.py
  integration_tests/test-requirements-for-tox.txt
  requirements.txt
  setup.py
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/config.py
  wazo_call_logd/controller.py
  wazo_call_logd/database/alembic.ini
  wazo_call_logd/database/alembic/__init__.py
  wazo_call_logd/database/alembic/env.py
  wazo_call_logd/database/alembic/script.py.mako
  wazo_call_logd/database/alembic/versions/5648242a2fee_create_recording_table.py
  wazo_call_logd/database/alembic/versions/__init__.py
  wazo_call_logd/database/database.py
  wazo_call_logd/database/models.py
  wazo_call_logd/database/queries/__init__.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/generator.py
  wazo_call_logd/init_db.py
  wazo_call_logd/main.py
  wazo_call_logd/main_sweep.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/plugin.py
  wazo_call_logd/plugins/cdr/schemas.py
  wazo_call_logd/plugins/cdr/services.py
  wazo_call_logd/raw_call_log.py
  wazo_call_logd/tests/test_cel_interpretor.py
  wazo_call_logd/tests/test_generator.py
  wazo_call_logd/tests/test_writer.py
  wazo_call_logd/writer.py
Labels: mergeit

#95 Pull request for WAZO-2202-download-delete-recording
  CHANGELOG.md
  Dockerfile
  debian/wazo-call-logd.postinst
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/database.py
  integration_tests/suite/helpers/filesystem.py
  integration_tests/suite/helpers/hamcrest/contains_string_ignoring_case.py
  integration_tests/suite/test_call_logs_cli.py
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_cdr_recording.py
  integration_tests/suite/test_db_call_log.py
  integration_tests/suite/test_db_recording.py
  wazo_call_logd/bus_client.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/exceptions.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/exceptions.py
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/plugin.py
  wazo_call_logd/plugins/cdr/schemas.py
  wazo_call_logd/plugins/cdr/services.py
  wazo_call_logd/plugins/support_center/exceptions.py
Labels: mergeit

#96 WAZO-2250 Pull request for extract-tenant-from-query
  integration_tests/suite/test_cdr_recording.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/schemas.py
Labels: auto-merge, mergeit

#97 Wazo 2203 filename to extract
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_cdr_recording.py
  integration_tests/suite/test_db_recording.py
  wazo_call_logd/database/models.py
  wazo_call_logd/database/queries/call_log.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/schemas.py
  wazo_call_logd/plugins/cdr/services.py
Labels: auto-merge, mergeit

#98 Pull request for fix-filename
  integration_tests/suite/test_cdr_recording.py
  integration_tests/suite/test_db_recording.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/services.py
Labels: mergeit

#99 Pull request for WAZO-2095-cdr-destination-group-queue-answered
  integration_tests/suite/test_call_log_generation.py
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/raw_call_log.py
Labels: auto-merge, mergeit

#100 Add queue destination uuid test
  integration_tests/suite/test_call_log_generation.py
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/raw_call_log.py
Labels: mergeit

#102 WAZO-2261: delete recording media
  CHANGELOG.md
  integration_tests/suite/helpers/database.py
  integration_tests/suite/helpers/filesystem.py
  integration_tests/suite/test_cdr_recording.py
  integration_tests/suite/test_db_recording.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/plugins/cdr/api.yml
  wazo_call_logd/plugins/cdr/http.py
  wazo_call_logd/plugins/cdr/services.py
Labels: mergeit

#101 Pull request for WAZO-2269-extract-call-log-from-dao
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_db_call_log.py
  integration_tests/suite/test_db_cel.py
  integration_tests/test-requirements-for-tox.txt
  wazo_call_logd/cel_fetcher.py
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/controller.py
  wazo_call_logd/database/cel_event_type.py
  wazo_call_logd/database/queries/__init__.py
  wazo_call_logd/database/queries/call_log.py
  wazo_call_logd/database/queries/cel.py
  wazo_call_logd/main_sweep.py
  wazo_call_logd/manager.py
  wazo_call_logd/tests/test_cel_fetcher.py
  wazo_call_logd/tests/test_cel_interpretor.py
  wazo_call_logd/tests/test_manager.py
  wazo_call_logd/tests/test_writer.py
  wazo_call_logd/writer.py
Labels: mergeit

#103 Pull request for WAZO-2239-migrate-cdr-db
  integration_tests/Makefile
  integration_tests/assets/docker-compose.migration.override.yml
  integration_tests/assets/docker-compose.yml
  integration_tests/assets/populate/migrate.sql
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/database.py
  integration_tests/suite/test_agent_stats.py
  integration_tests/suite/test_call_log_generation.py
  integration_tests/suite/test_call_logd_migrate_db.py
  integration_tests/suite/test_call_logs_cli.py
  integration_tests/suite/test_cdr.py
  integration_tests/suite/test_db.py
  integration_tests/suite/test_db_call_log.py
  integration_tests/suite/test_db_cel.py
  integration_tests/suite/test_db_recording.py
  integration_tests/suite/test_db_tenant.py
  integration_tests/suite/test_documentation.py
  integration_tests/suite/test_queue_stats.py
  integration_tests/suite/test_recording_generation.py
  integration_tests/suite/test_status.py
  setup.py
  tox.ini
  wazo_call_logd/cel_interpretor.py
  wazo_call_logd/database/alembic/versions/19f58ac91ae1_add_call_log_tables.py
  wazo_call_logd/database/alembic/versions/cbd0bbfb6dd8_add_foreign_key_recording_call_log.py
  wazo_call_logd/database/models.py
  wazo_call_logd/database/queries/__init__.py
  wazo_call_logd/database/queries/call_log.py
  wazo_call_logd/database/queries/cel.py
  wazo_call_logd/database/queries/recording.py
  wazo_call_logd/database/queries/tenant.py
  wazo_call_logd/main_migrate_db.py
  wazo_call_logd/manager.py
  wazo_call_logd/plugins/cdr/services.py
  wazo_call_logd/raw_call_log.py
  wazo_call_logd/writer.py
Labels: mergeit

#105 Pull request for WAZO-2240-purge-cdr
  etc/wazo-purge-db/conf.d/50-call-logd.yml
  integration_tests/suite/test_purger.py
  setup.py
  wazo_call_logd/purger.py
Labels: auto-merge
